apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{NAMESPACE}}-ingress
  namespace: {{NAMESPACE}}
spec:
  rules:
  - host: {{NAMESPACE}}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              number: 80
